// <auto-generated />
namespace Hospital_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202010191557303_removeProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
